#!/usr/bin/env python3
"""Build assets/textures.js from the NASA-derived Earth maps shipped in the
`three-globe` npm package (MIT; imagery is NASA Blue Marble / Earth at Night,
public domain).

    npm pack three-globe && tar -xzf three-globe-*.tgz
    python3 tools/make_textures.py path/to/package/example

Produces compact JPEGs and embeds them as data URIs so the page works from
file://, GitHub Pages or a sandboxed artifact with no network requests.
"""
import base64
import io
import os
import sys

import numpy as np
from PIL import Image, ImageFilter

SRC = sys.argv[1] if len(sys.argv) > 1 else 'package/example'
OUT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'textures.js')


def jpeg(img, quality, **kw):
    buf = io.BytesIO()
    img.save(buf, 'JPEG', quality=quality, optimize=True, progressive=True, **kw)
    return buf.getvalue()


def main():
    out = {}

    # Day side: Blue Marble.
    day = Image.open(os.path.join(SRC, 'img', 'earth-blue-marble.jpg')).convert('RGB')
    day = day.resize((4096, 2048), Image.LANCZOS)
    out['day'] = jpeg(day, 76, subsampling='4:2:0')

    # City lights: the source is a blue-tinted night map with orange lights.
    # The red channel isolates the lights from the blue base layer.
    night = np.asarray(Image.open(os.path.join(SRC, 'img', 'earth-night.jpg')).convert('RGB')).astype(np.float32)
    r, b = night[..., 0], night[..., 2]
    lights = np.clip((r - 0.22 * b - 8.0) / 110.0, 0.0, 1.0) ** 1.15
    lights_img = Image.fromarray((lights * 255).astype(np.uint8), 'L').resize((4096, 2048), Image.LANCZOS)
    out['lights'] = jpeg(lights_img, 82)

    # Clouds: coverage lives in the alpha channel of a paletted PNG.
    clouds = np.asarray(Image.open(os.path.join(SRC, 'clouds', 'clouds.png')).convert('RGBA'))[..., 3]
    clouds_img = Image.fromarray(clouds, 'L').resize((2048, 1024), Image.LANCZOS)
    out['clouds'] = jpeg(clouds_img, 80)

    # Water mask (white = ocean), softened a touch so coastlines don't alias.
    water = Image.open(os.path.join(SRC, 'img', 'earth-water.png')).convert('L').resize((1024, 512), Image.LANCZOS)
    water = water.filter(ImageFilter.GaussianBlur(0.6))
    out['water'] = jpeg(water, 80)

    lines = ['/* Generated by tools/make_textures.py — NASA Blue Marble, Earth at Night and',
             ' * cloud imagery (public domain) via the three-globe package. Do not edit. */',
             'window.CA_TEXTURES = {']
    total = 0
    for key, data in out.items():
        total += len(data)
        b64 = base64.b64encode(data).decode('ascii')
        lines.append("  %s: 'data:image/jpeg;base64,%s'," % (key, b64))
        print('%-7s %8.1f KB' % (key, len(data) / 1024))
    lines.append('};')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('total   %8.1f KB raw, %8.1f KB as base64' % (total / 1024, total * 4 / 3 / 1024))


if __name__ == '__main__':
    main()
